### PR TITLE
Setup for environment variable handling

### PR DESCRIPTION
**Pull request by MasonAdkins**
**EDIT: this comment is moot due to changes made later in the PR.**

I made a couple easy modifications so that the project can use environment variables moving forward.

Few things to note:
1. you **need** to create a local file named **.env** inside your project directory
2. Make sure to ` pip install -r requirements.txt` to install the additional library (both locally and on heroku)
3. The variables will need to be added in the Heroku settings as well
4. Most importantly, on Heroku you'll want to set debug to **False** for security reasons.

Here is all you need in your local **.env** file for now:
```
DEBUG=True
SECRET_KEY=ja391197!tv&r$qbptd10(ecx0visy&ur#*)se&+*j(+v9#fbp
```
You can now leave your local debug set to True and it will automatically fill with False on Heroku.

### CODE REVIEW

**Comment by MasonAdkins** [comment]
@kfwojton I did some reading on the subject and I landed on python-decouple because its adds some additional features on top of directly using environment variables. The default os.environ.get() method always returns a string which can potentially not be ideal (like the case with debug being a boolean value). 

 I don't mind rewriting it to reflect your comments, but could you provide some clarification on why that is your preference?

**Comment by kfwojton** [comment]
@MasonAdkins great points. The reason I am suggesting os.environ.get(), is that all of the env variables should be strings. The debug value is too important ot leave up to an env, it usually best practice to keep debug as False so anyone can look at the code base and immediately see, ok debug=False we are good. The other way only people who have access to the server settings could check it. Because this is the only non-string variable and we are using .env for string variables we can use os.environ.get. The other reason besides the importance of making debug = False is that our main job as developers is to lower the "mental overhead" of a code base. Thus the best implementation is one that is the most easy to understand, not the most elegant code. My opinon is that this `config('DEBUG', cast=bool)` is just a hair harder to unwind than `os.environ.get()`. I would immediately look up the documentation on config, to be like what is cast mean? Why use cast instead of just the python built in `bool()`. Just some thoughts. 

This code review feedback is just a suggestion, not a hard "must change" comment. It is up to you and Ashley, the codebase owner, to decide which implementation is best.

**Comment by kfwojton** [comment]
@MasonAdkins great points. The reason I am suggesting os.environ.get(), is that all of the env variables should be strings. The debug value is too important ot leave up to an env, it usually best practice to keep debug as False so anyone can look at the code base and immediately see, ok debug=False we are good. The other way only people who have access to the server settings could check it. Because this is the only non-string variable and we are using .env for string variables we can use os.environ.get. The other reason besides the importance of making debug = False is that our main job as developers is to lower the "mental overhead" of a code base. Thus the best implementation is one that is the most easy to understand, not the most elegant code. My opinon is that this `config('DEBUG', cast=bool)` is just a hair harder to unwind than `os.environ.get()`. I would immediately look up the documentation on config, to be like what is cast mean? Why use cast instead of just the python built in `bool()`. Just some thoughts. 

This code review feedback is just a suggestion, not a hard "must change" comment. It is up to you and Ashley, the codebase owner, to decide which implementation is best.

**Comment by MasonAdkins** [comment]
Everything should be good for merging.

**Pull request merged**
